/**<----------All subsequences of th string is------------>
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a 
 * given String, that is generated by deleting some character of a given string without changing 
 * its order.
 * */
//yet to do it
//whatever will finish it today
#include <bits/stdc++.h>
using namespace std;


void printSequences(string input,string output);

int main()
{   cout<<"{";
    printSequences("abc","");
    cout<<"\b}"<<endl;
    return 0;
}

void printSequences(string input,string output="")
{
    if(input.empty())
    {
        cout<<"{"<<output<<"}"<<",";
        return ;
    }

    printSequences(input.substr(1),output+input[0]);
    printSequences(input.substr(1),output);
}
